//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAllowance
    {
        public short AllowanceID { get; set; }
        public string AllowanceName { get; set; }
        public double AllowanceAmount { get; set; }
        public string AllowanceRemarks { get; set; }
    }
}
